---
# Setup Galaxy Trackster
#
#   https://wiki.galaxyproject.org/VisualizationSetup

- name: Assure Trackster len files dir exists
  file: state=directory path="{{ len_file_path }}"  #"

- name: Download .len files
  get_url: url=https://s3.amazonaws.com/cloudman/files/len-files.tar.gz dest=/tmp/len-files.tar.gz timeout=30

- name: Unarchive .len files
  unarchive: copy=no src=/tmp/len-files.tar.gz dest={{ len_file_path }}

- name: Assure generic tools bin dir exists
  file: state=directory path={{ galaxyFS_base_dir }}/tools/bin

- name: Download Trackster-required utilities
  get_url: url={{ item }} dest={{ galaxyFS_base_dir }}/tools/bin/ mode=0755
  with_items:
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit

- name: Download bedtools source
  get_url: url=https://github.com/arq5x/bedtools2/releases/download/v{{ bedtools_version }}/bedtools-{{ bedtools_version }}.tar.gz dest=/tmp/bedtools2.tar.gz

- name: Extract bedtools source
  unarchive: copy=no src=/tmp/bedtools2.tar.gz dest=/tmp/

- name: Make bedtools
  command: chdir=/tmp/bedtools2-{{ bedtools_version }} make

- name: Copy bedtools binaries
  shell: cp /tmp/bedtools2-{{ bedtools_version }}/bin/* {{ galaxyFS_base_dir }}/tools/bin/.

- name: Remove downloaded bedtools tarball
  file: path=/tmp/bedtools2.tar.gz state=absent

- name: Remove tmp bedtools dir
  file: path=/tmp/bedtools2-{{ bedtools_version }} state=absent
